title: Pincent

description: Pincent

url: http://www.pincent.net

permalink: /:categories/:title.html

relative_permalinks: false

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  cache: true
  cache_assets: true
  gzip: []

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md

product_categories:
  cab:
    - 醋酸丁酸纤维素(CAB)
    - cab
    - cellulose_acetate_butyrate.jpg
  dispersant:
    - 分散剂
    - dispersant
    - cellulose_acetate_butyrate.jpg
