title: 佛山市品诚贸易有限公司

keywords: "品诚, 品诚贸易, 化工, 化工贸易, 涂料, 油墨, 日用化学品, 化工原材料"

description: 佛山市品诚贸易有限公司主要从事化工贸易，代理销售国内外化工原材料，是国内专业的涂料、油墨及日用化学品原料供货商。

url: http://www.pincent.net

permalink: /:categories/:title.html

relative_permalinks: false

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  cache: true
  cache_assets: true
  gzip: []

exclude:
  - Dockerfile
  - Makefile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md

product_categories:
  cab:
    - 醋酸丁酸纤维素(CAB)
    - cab
    - cellulose_acetate_butyrate.jpg
  dispersant:
    - 分散剂
    - dispersant
    - dispersant.jpg
  vinyl_resin:
    - 氯醋树脂
    - vinyl_resin
    - vinyl_resin.jpg
  glass_powder:
    - 玻璃粉
    - glass_powder
    - glass_powder.jpg
  cellulose:
    - 纤维素
    - cellulose
    - cellulose.jpg
  adhesion_promoter:
    - 附着力促进剂
    - adhesion_promoter
    - adhesion_promoter.jpg
  paint:
    - 油漆
    - paint
    - paint.jpg
